# Generated by Django 5.0.4 on 2024-04-16 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.IntegerField()),
                ('lead', models.BooleanField(default=False)),
                ('project_send_attempt', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('rests', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('style', models.CharField(max_length=50)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
