# Generated by Django 5.0.4 on 2024-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_session_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionId',
            field=models.IntegerField(blank=True),
        ),
    ]
