# Generated by Django 5.0.4 on 2024-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_session_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionId',
            field=models.IntegerField(default=0),
        ),
    ]
